### ISSUE TITLE
fix: Can't re download a external vendor scripts on :copy 

### ISSUE THREAD

**Issue by meezyart** [pyramidium/generator-bannertime#118]
getting this error message

 Include vendor scripts for offline use? Yes
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: **Download is not a constructor**
    at Bannertime.files (/usr/local/lib/node_modules/generator-bannertime/generators/new/modules/files.js:162:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-bannertime/node_modules/yeoman-generator/lib/index.js:399:25)
    at /usr/local/lib/node_modules/generator-bannertime/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)

**Comment by joemidi** [comment]
Sorry about that, it looks like we swapped out the Download package with a newer one and forgot to update the script in the copy generator.
