### ISSUE TITLE
Getting an error while setting up a project.

### ISSUE THREAD

**Issue by lipovskoy** [pyramidium/generator-bannertime#139]
Hi! Im getting an error while setting up a project:

ReferenceError: primordials is not defined
    at fs.js:52:5
    at req_ (/Users/admin/www/test/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/admin/www/test/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/admin/www/test/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)

**Comment by lipovskoy** [comment]
Problem solved by using Node 10.0.0
