### ISSUE TITLE
Getting an error when including vendor scripts for offline use

### ISSUE THREAD

**Issue by listentoyoureyes** [pyramidium/generator-bannertime#80]
Im getting this error when i choose yes in the Include vendor scripts for offline use? dialog.

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Download is not a constructor
    at Bannertime.files (/usr/local/lib/node_modules/generator-bannertime/generators/app/modules/files.js:176:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-bannertime/node_modules/yeoman-generator/lib/index.js:408:23)
    at /usr/local/lib/node_modules/generator-bannertime/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/generator-bannertime/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-bannertime/node_modules/yeoman-generator/lib/index.js:409:9
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by joemidi** [comment]
Ah it seems that they've [Promisified](https://github.com/kevva/download/pull/103) it now.

We'll update this soon.
