### ISSUE TITLE
error: RequestError: getaddrinfo ENOTFOUND function function:80

### ISSUE THREAD

**Issue by joemidi** [pyramidium/generator-bannertime#85]
```
 |     |___ ___ _ _| |_|_|_____ ___
 |   --| . | . | | |  _| |     | -_|
 |_____|___|  _|_  |_| |_|_|_|_|___|
           |_| |___|

RequestError: getaddrinfo ENOTFOUND function function:80
    at ClientRequest.req.once.err (/Users/joeypadasian/.nvm/versions/node/v6.7.0/lib/node_modules/generator-bannertime/node_modules/got/index.js:73:21)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1015:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by joemidi** [comment]
I ended up uninstalling my `npm` versions of `yo` and `bannertime` and installed them via `yarn` instead.
